---
#
# Ansible managed
#
repository:
  description: Install and configure xinetd on your system.
  homepage: https://buluma.github.io/
  topics: daemon, installer, networking, system, xinetd, ansible, molecule, tox, playbook, hacktoberfest
